apiVersion: apps/v1
kind: Deployment
metadata: 
  name: alpine-kube2
spec:
  selector: 
    matchLabels:
      app: alpine-kube2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alpine-kube2
      spec:
        nodeName: worker1
        containers:
        - image: alpine
          name: alpine
          stdin: true
          tty: true
  