---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  podSubnet: "10.244.0.0/16" # Update to match your Tigera Calico CIDR
  serviceSubnet: "10.96.0.0/16" # Default service subnet
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "192.168.80.58" # Update this with your control plane's private IP
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    node-ip: "192.168.80.58"

